# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdd078769f394d39b940c4dfa39c951790da6c623cef8a1f423e51ee61bf1f54ae9a89b91b8c95a9aba71922dca55f9e1dd11a746fedc8e940bf8052ff05b06c

test:
  secret_key_base: ce552bba7c38bea9badf838f56d2225f60d916b855603b8f3e5296818a6d697d8923930290930463baefe076f15797f42675ba7f69a5f786e2e81488b8afe173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
